#spring.application.name=user-service
#server.error.include-stacktrace=on_param

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: valente
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true

server:
  error:
    include-stacktrace: on_param
#  servlet:
#    context-path: /
  tomcat:
    threads:
      max: 20

logging:
  level:
#    dev.valente.user_service: debug
    #    org.hibernate.orm.jdbc.bind: trace
#    net.ttddyy.dsproxy.listener: debug
    org.springframework.security: debug
