#spring.application.name=user-service
#server.error.include-stacktrace=on_param

spring:
  application:
    name: user-service
  threads:
    virtual:
      enabled: true

server:
  error:
    include-stacktrace: on_param
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 20

logging:
  level:
    dev.valente.user_service: debug

